- backend_dir_name: bert_classifier
  backend_tag_prefix: bertclass-
- backend_dir_name: easyocr
  backend_tag_prefix: easyocr-
- backend_dir_name: flair
  backend_tag_prefix: flair-
- backend_dir_name: grounding_dino
  backend_tag_prefix: grnddino-
  runs_on: ubuntu-latest-4c-16gb
- backend_dir_name: grounding_sam
  backend_tag_prefix: grounding_sam-
  runs_on: ubuntu-latest-4c-16gb
- backend_dir_name: huggingface_llm
  backend_tag_prefix: huggingfacellm-
- backend_dir_name: huggingface_ner
  backend_tag_prefix: huggingfacener-
- backend_dir_name: interactive_substring_matching
  backend_tag_prefix: interactsubstrmatch-
- backend_dir_name: langchain_search_agent
  backend_tag_prefix: langchainsearch-
- backend_dir_name: llm_interactive
  backend_tag_prefix: llm-
- backend_dir_name: mmdetection-3
  backend_tag_prefix: mmdetection3-
  runs_on: ubuntu-latest-4c-16gb
- backend_dir_name: nemo_asr
  backend_tag_prefix: nemoasr-
- backend_dir_name: segment_anything_model
  backend_tag_prefix: sam-
- backend_dir_name: segment_anything_2_image
  backend_tag_prefix: sa2-
  runs_on: ubuntu-latest-4c-16gb
  bypass:
    - pytests
- backend_dir_name: segment_anything_2_video
  backend_tag_prefix: segment_anything_2_video-
  runs_on: ubuntu-latest-4c-16gb
  bypass:
    - pytests
- backend_dir_name: sklearn_text_classifier
  backend_tag_prefix: sklearntxtclass-
- backend_dir_name: spacy
  backend_tag_prefix: spacy-
- backend_dir_name: tesseract
  backend_tag_prefix: tesseract-
- backend_dir_name: yolo
  backend_tag_prefix: yolo-
